# Generated by Django 4.0 on 2021-12-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('status', models.CharField(default='new', max_length=200, verbose_name='Статус')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
            ],
            options={
                'verbose_name': 'Список дел',
                'verbose_name_plural': 'Списки дел',
                'db_table': 'to_do_lists',
            },
        ),
    ]
