# Generated by Django 4.0 on 2021-12-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todolist',
            table='ToDoList',
        ),
    ]
