# Generated by Django 4.0 on 2021-12-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_list', '0002_alter_todolist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todolist',
            table='ToDoLists',
        ),
    ]
