# Generated by Django 4.0 on 2022-01-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_list', '0004_alter_todolist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
    ]
